# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Gnews
tagline:             'Software, tech & stuff'
description:         ''
url:                 http://capravictoriae.github.io/gnews
baseurl:             '/gnews'
paginate:            1
gems: 				 [jekyll-paginate]

# About/contact
author:
  name:              PF
  url:               https://github.com/capravictoriae/gnews
  email:             p@p.com

# Custom vars
version:             1.0.0
